name: 'dbt_fabric_project'
version: '1.0.0'

profile: 'dbt_fabric_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  bronze_schema: bronze
  silver_schema: silver
  gold_schema: gold

models:
  dbt_fabric:
    silver:
      +materialized: table
      +schema: silver

    gold:
      +materialized: table
      +schema: gold
